#!/usr/bin/env bash
# Install Nginx with custom configuration.

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World" > /etc/nginx/html/index.html
service nginx restart
