#!/usr/bin/env bash
# Install Nginx with custom configuration.

sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/index.html
sudo service nginx start
