#!/usr/bin/env bash
# Confgure web-02 to be identical to web-01

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "Holberton School" > /var/www/html/index.html

sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}\n"
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
err_page="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $err_page" /etc/nginx/sites-available/default
sudo service nginx start
sudo service nginx reload