#!/usr/bin/env bash
# Displays "Holberton School" 10 times using a while loop.
# Displays bad luck for the 4th loop iteration.
# Displays good luck for the 8th loop iteration.

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 4 ]
	then
	    echo "bad luck"
	elif [ $i -eq 8 ]
	then
	    echo "good luck"
	else
	    echo "Holberton School"
	fi
	(( i++ ))
done
