#!/usr/bin/env bash
# Run Apache on the holbertonschool/265-0 Docker container.
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install apache2 apache2-doc apache2-utils
sudo service apache2 start
